slevithan/xregexp

bower.json
Add bower.json to support bower.io
Most fields were copied from package.json but wasn't sure what to add for ```dependencies``` and ```devDependencies```.  Explanation for what to put in those fields is at http://bower.io/docs/creating-packages/
You will also need to register the XRegExp package with bower once bower.json has been added, using the instructions provided at the above link.
#63 #78
=> bower.json

tools/intro.js, xregexp-all.js
The Firefox Addon SDK defines a global `define` function, which XRegExp's UMD stanza mistakes for AMD. Adding a check for `define.amd` fixes this and is the standard way to detect AMD:
https://github.com/umdjs/umd/blob/3e14a7dfb0af2bd3a8bfe9b7b384d698e3ef75e4/amdWeb.js#L19
=> fix AMD detection

src/xregexp.js
This makes it clearer that the `XRegExp` function is being referred to instead of `self`, which is also a reference to the global variable. (I was a little confused by this initially when I read the code for one of the functions without looking at the first few lines. Hope this makes it clearer for others.)
=> Rename `self` to `XRegExp`.

src/xregexp.js, tests/spec/s-xregexp.js
This fixes https://github.com/slevithan/xregexp/issues/112
The new cleanup regex also cleans up `*`, `+`, `?` or `{\d}` after an empty capture group. 
You can see a demo here: http://rubular.com/r/AFFiDroJEg
=> GH-112 Allow (?:)*/+/?/{1} without causing a syntax error

src/addons/build.js, src/xregexp.js, xregexp-all.js
The Duktape JavaScript engine is very strict when it comes to regex literals.
It was choking on two regexs in the XRegExp source. This commit correctly escapes
two closing square brackets that should be escaped because they don't have an opening
counterpart and they should be matched as a literal character.
=> Correctly escape closing square brackets in two regular expression literals

src/xregexp.js
follow-up on commit SHA-1: f5dbc86a9fb6657f8323d814534d9ae92436c8b7 (:: Correctly escape closing square brackets in two regular expression literals.) --> one more regex with an escaped = *literal* square bracket.
=> follow-up on commit SHA-1: f5dbc86a9fb6657f8323d814534d9ae92436c8b7 (escaping literal brackets)

tests/perf/index.html, tests/perf/perf.js, tests/vendor/benchmark.js/LICENSE.txt, tests/vendor/benchmark.js/README.md, tests/vendor/benchmark.js/benchmark.js, tests/vendor/benchmark.js/lodash.js, tests/vendor/benchmark.js/platform.js
migrated performance tests to use latest BenchmarkJS v2.1.1 (which requires lodash and optional platform libraries to be loaded as well: these are included in the tests/vendor/benchmark.js/ directory)
=> migrated performance tests to use latest BenchmarkJS v2.1.1

src/addons/unicode-base.js
added API `XRegExp.isUnicodeSlug(name)` which checks whether a given `name` is a recognized Unicode Slug, e.g. `Number` (but not `Numeric` as `\p{Numeric}` is an _invalid_ Unicode `\p` regex slug.  This API is used by the GerHobbelt/jison app to help add Unicode support to the grammars being compiled. The way the API internals (**and documentation**, see the comment block in the patch) is written, i.e. that rather than a plain `true` boolean value, a 'truthy' Unicode slug definition is produced, is also used by the GerHobbelt/jison app: that code generator uses this artifact to greatly simplify lexer regex expansion and rewriting.
=> added API `XRegExp.isUnicodeSlug(name)` which checks whether a given `name` is a recognized Unicode Slug

src/xregexp.js, xregexp-all.js
[Baseline (build of the current master)](https://github.com/pygy/xregexp/blob/c28faa33c5be869e68e626da27021d35d1a02793/tests/perf/index.html)
[Proposed patch](https://cdn.rawgit.com/pygy/xregexp/8f8acf728ec840e35868b5a62e54878ac99a7465/tests/perf/index.html)
[Test suite post-build](https://cdn.rawgit.com/pygy/xregexp/8f8acf728ec840e35868b5a62e54878ac99a7465/tests/index.html)
I've only tested this in an old Chromium build so far that doesn't have `y`. The sticky benchmark performance is one order of magnitude better.
I've also had 2x improvements in the non-cache/non-flush XRegExp constructor tests, but they are not reliably reproducible.
I'll try it in SauceLabs later today for older IE versions.
Edit: one order of magnitude, not "orders"... Still, better ;-). Sticky matching goes from …
=> Optimize sticky matching

src/addons/build.js, src/addons/matchrecursive.js, src/addons/unicode-base.js, src/xregexp.js
... with `@private` and `@memberOf` tags for XRegExp and (obsoleted) natives overrides by XRegExp.
=> completed JSDoc et al documentation markup 

src/xregexp.js, xregexp-all.js
As discussed previously in #152 and #153
=> Don't allocate the sticky regex source when the resulting regexp is already cached

.editorconfig
It looks like comments have manually been wrapped to 100 characters, so
use that as the [max_line_length] in the .editorconfig file.
[max_line_length]: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length
=> Add max_line_length to .editorconfig

package.json, tests/helpers/h-unicode.js, tests/helpers/h.js, tests/jasmine.json
This is a follow-up to https://github.com/slevithan/xregexp/pull/155#issuecomment-279608958
that lets the tests run in Node, without opening a browser. It's set up
so that opening tests/index.html still works, for anyone who prefers
that workflow.
See the jasmine docs for more info on using it with Node: https://jasmine.github.io/2.5/node.html
=> Make tests run in Node

.editorconfig, .travis.yml, README.md
Following up on https://github.com/slevithan/xregexp/pull/155#issuecomment-279614509,
here are some changes that set up [Travis CI] for this repo. To enable
it, all you'll need to do is sign in to Travis using Github, then go to
your [profile] and hit the switch beside `slevithan/xregexp`. Here's an
example of what a build looks like: https://travis-ci.org/josephfrazier/xregexp/builds/201410109
[Travis CI]: https://travis-ci.org/
[profile]: https://travis-ci.org/profile/slevithan
=> Add Travis CI configuration

src/addons/build.js, tests/spec/s-addons-build.js, xregexp-all.js
This fixes https://github.com/slevithan/xregexp/issues/162 by making
sure that all the flags passed to `XRegExp.build` make it to the
`XRegExp()` call, rather than just the flags used as leading mode
modifiers in the pattern.
=> Pass XRegExp.build flags through asXRegExp to XRegExp constructor

package.json
While `xregexp-all.js` exists in the repo, it isn't included in the npm install. Adding the file to the package.json ensures npm installs provide a production-ready version for non-node applications.
This PR fixes #139
=> Include build package in package.json for npm installs.

src/xregexp.js, xregexp-all.js
Closes https://github.com/slevithan/xregexp/issues/158
This reverts commit 660f3acd8d81b9282d12385205fca0a7e07e222a.
=> Revert "Work around bug in Safari Technology Preview /y support -- closes #135"

src/addons/build.js, src/addons/matchrecursive.js, src/xregexp.js, tests/spec/s-xregexp-methods.js, xregexp-all.js
The `XRegExp.union` calls in the `build` and `matchRecursive` addons are
also updated to explicitly specify `{conjunction: 'or'}`.
Fixes https://github.com/slevithan/xregexp/issues/106
=> Add `conjunction` option for XRegExp.union and allow setting to 'none'

src/xregexp.js, xregexp-all.js
As seen in https://github.com/slevithan/xregexp/issues/107:
> * Change `<li>`s to asterisks or hyphens in code comments.
I used hyphens rather than asterisks because each comment line already
starts with an asterisk, so hyphens visually stand out more.
=> Change `<li>`s to hyphens in code comments

src/addons/build.js, src/addons/matchrecursive.js, src/xregexp.js, xregexp-all.js
This partially addresses the following item in https://github.com/slevithan/xregexp/issues/107:
> * New `var` on each line, and don't always declare vars at top of
function.
The change was made with the help of [lebab], by running:
lebab --replace src --transform multi-var
[lebab]: https://github.com/lebab/lebab
=> Declare each `var` on a separate line

src/xregexp.js, tests/spec/s-xregexp.js, xregexp-all.js
This simplifies the compiled expressions by ensuring that groups don't
start or end with `(?:)`. For instance, this code:
```js
// Using named capture and flag x (free-spacing and line comments)
date = XRegExp('(?<year>  [0-9]{4} ) -?  # year  \n' +
'(?<month> [0-9]{2} ) -?  # month \n' +
'(?<day>   [0-9]{2} )     # day     ', 'x');
```
now compiles to this pattern:
```regex
([0-9]{4})(?:)-?(?:)([0-9]{2})(?:)-?(?:)([0-9]{2})(?:)
```
instead of
```regex
((?:)[0-9]{4}(?:))(?:)-?(?:)((?:)[0-9]{2}(?:))(?:)-?(?:)((?:)[0-9]{2}(?:))(?:)
```
Here are the two patterns side by side, with whitespace inserted into the new one to illustrate the differences:
```regex
(    [0-9]{4}    )(?:)-?(?:)(    [0-9]{2}    )(?:)-?(?:)(    [0-9]{2}    )(?:) …
```
=> Cleanup (?:) from beginning/end of groups

.babelrc, package.json, src/xregexp.js, xregexp-all.js
This makes the "Constructor with x flag, whitespace, and comments" test
fast again. From
https://github.com/slevithan/xregexp/pull/164#issuecomment-294345042:
> A couple ideas: avoid the string concatenation in `isPatternNext`
> (possibly going back to regex literals and making the function specific
> to quantifiers again even though the current code is more
> readable/maintainable, since this isn't needed to handle simple cases
> with whitespace followed by `)`)
Since [babel-plugin-transform-xregexp] automatically compiles the `new
RegExp()` calls into literals, we get (most of) the performance back
without sacrificing the readability of having separate subpatterns.
[babel-plugin-transform-xregexp]: https://www.npmjs.com/package/babel-plugin-transform-xregexp
=> Revert isPatternNext to isQuantifierNext

src/addons/build.js, tests/spec/s-addons-build.js, xregexp-all.js
Fixes https://github.com/slevithan/xregexp/issues/103
=> Add XRegExp.tag in `build` plugin for tagged template string construction

src/xregexp.js, tests/spec/s-xregexp-natives.js, xregexp-all.js
Fixes https://github.com/slevithan/xregexp/issues/177
I had some trouble using a single regex for the replacement, so I replaced
the $<name> syntax first in a separate pass.
=> Add $<n> and $<name> as alternative backreference syntax in replacement text

.eslintrc.js, package.json
This will make it easier to automatically enforce the pre-existing code
style of the project, using [eslint]. It was done by running:
npm install --save-dev eslint
./node_modules/.bin/eslint --init
[eslint]: https://github.com/eslint/eslint/
This script interactively generates an eslint configuration (see [here]).
Here's how I answered its questions:
* Choosing `Inspect your JavaScript file(s)`
* Entering `src` as the files to inspect
* Choosing a JavaScript config file format
* Answering yes to ES6 features/classes
* Choosing both Node/Browser as environment
* Answering yes to CommonJS
* Answering no to JSX/React
[here]: http://devnull.guru/adding-eslint-to-your-project-is-easier-than-ever/
After that, I added the `lint` script to package.json, and manually
changed the …
=> Add eslint to enforce code style

README.md
This clarifies where xregexp-all.js can be found, now that it is no
longer in the repository (https://github.com/slevithan/xregexp/pull/187)
=> README: Add unpkg.com references for xregexp-all.js

tests/helpers/h.js
This fell out of use in 8e6244cd215f251ba6589ea5324f0a667698e8f2,
but it wasn't removed there.
=> tests: Remove unused `repeat()` helper

src/xregexp.js, tests/spec/s-xregexp.js
Following up on https://github.com/slevithan/xregexp/pull/164, this
change prevents a `(?:)` from being inserted in the following places:
* At the beginning of a non-capturing group or (negated) lookahead (the end is already handled)
* Before or after a `|`
* At the beginning or the end of the pattern
This solution isn't as complete as the one suggested in
https://github.com/slevithan/xregexp/issues/179, but it's a decent
stopgap.
=> Cleanup more `(?:)` from patterns

src/xregexp.js, tests/helpers/h.js, tests/spec/s-xregexp-methods.js
This addresses https://github.com/slevithan/xregexp/issues/175
I still need to add proper tests, but the new behavior can be
demonstrated by running this after `npm run build`
```js
var XRegExp = require('./')
XRegExp.install('namespacing')
var regex = XRegExp('(?s)(?<__proto__>.)');
var match = XRegExp.exec('test', regex);
console.log(match)
const replaced = XRegExp.replace('test', regex, function (matched, capture1, position, S, groups) {
console.log({groups})
})
```
=> [WIP] Add `namespacing` feature for named capture groups object

src/addons/unicode-base.js, src/xregexp.js
- Refactoring: Fix ESLint issue with preferring `const`; bring `let` closer to utilizing scope, destructure
=> ESLint refactoring

.eslintrc.js, src/addons/matchrecursive.js, src/xregexp.js
This is a follow-up to https://github.com/slevithan/xregexp/pull/236
We could also do array destructuring, but it looked a little
weird to me, so I left it out for now.
EDIT: Enforcing array destructuring also touches files in `tools/`, and I'm not sure if we have a reason not to do that. See https://github.com/slevithan/xregexp/pull/236#issuecomment-382510746
=> ESLint: Enforce object destructuring

.eslintrc.js, src/xregexp.js, tools/scripts/utils.js
This is a follow-up to https://github.com/slevithan/xregexp/pull/237
=> ESLint: Enforce array destructuring

.travis.yml
v10 fails currently: https://travis-ci.org/slevithan/xregexp/builds/370310563#L510-L528
```
Failures:
1) XRegExp() supports new regex syntax: named capture should throw an exception if characters other than A-Z, a-z, 0-9, $, and _ are used in capture names
Message:
Expected function to throw an Error.
Stack:
Error: Expected function to throw an Error.
at UserContext.<anonymous> (/home/travis/build/slevithan/xregexp/tests/spec/s-xregexp.js:407:61)
Message:
Expected function to throw an Error.
Stack:
Error: Expected function to throw an Error.
at UserContext.<anonymous> (/home/travis/build/slevithan/xregexp/tests/spec/s-xregexp.js:408:63)
Message:
Expected function to throw an Error.
Stack:
Error: Expected function to throw an Error.
at UserContext.<anonymous> …
```
=> Pin Travis to Node v9 to avoid v10 failures

.babelrc, package-lock.json, package.json
Fixes https://github.com/slevithan/xregexp/issues/279
=> Upgrade to @babel/runtime-corejs3

package.json
This will allow users to consume the original esm modern code. This would make #275 a minor non-blocking issue. :)
=> Add `module` to package.json for rollup/webpack

src/addons/matchrecursive.js, src/xregexp.js
Alternatively use primitive type instead of nullable boxed type.
=> Add non-nullable modifier to return type of functions never returning null

package.json
This should close https://github.com/slevithan/xregexp/issues/305, see https://github.com/slevithan/xregexp/issues/305#issuecomment-740353997:
> Actually, after reading https://webpack.js.org/configuration/resolve/#resolvemainfields more closely, it sounds like adding a `browser` field to `package.json`, that points to `lib/index.js` (same as `main`) should fix things.
>
> > resolve.mainFields
> > [string]
> >
> > When importing from an npm package, e.g. import * as D3 from 'd3', this option will determine which fields in its package.json are checked. The default values will vary based upon the target specified in your webpack configuration.
> >
> > When the target property is set to webworker, web, or left unspecified:
> >
> > webpack.config.js
> >
> > module.exports = {
> >   //...
> > …
=> Add browser field to package.json to fix webpack

.github/workflows/build.yml, .travis.yml, README.md, package-lock.json, package.json
Travis CI is no longer providing CI minutes for open source projects: https://news.ycombinator.com/item?id=25338983
It's also been pretty slow: the build for https://github.com/slevithan/xregexp/pull/308
hasn't started in 13 minutes
The config file is based on the template at https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs#specifying-the-nodejs-version
=> Use GitHub Actions instead of Travis CI

README.md, package-lock.json, package.json, src/addons/build.js, src/addons/matchrecursive.js, src/addons/unicode-base.js, src/addons/unicode-blocks.js, src/addons/unicode-categories.js, src/addons/unicode-properties.js, src/addons/unicode-scripts.js, src/xregexp.js
Changes include:
~* Remove no longer relevant lastIndex code from replace method, fixes https://github.com/slevithan/xregexp/issues/287~
* Add browser field to package.json to fix webpack: https://github.com/slevithan/xregexp/pull/308
To generate this commit, I adapted the steps at https://github.com/slevithan/xregexp/pull/205#issuecomment-354236652
Here's a fuller list of changes that can be needed with new releases:
> * Version number
>   * Update version number and year in headers, config files, README.
>   * Update year in LICENSE.
>   * Update version number in `XRegExp.version`.
> * Publish
>   * Publish new git tag. E.g.:
>     * `git tag -a v3.1.0 -m "Release 3.1.0"`.
>     * `git push origin v3.1.0`.
>   * `npm publish`.
(closes https://github.com/slevithan/xregexp/pull/311)
=> Bump version to 4.4.1

.gitignore, package-lock.json, package.json
It also prints it out after the tests like this:
```
=============================== Coverage summary ===============================
Statements   : 74.02% ( 1946/2629 )
Branches     : 54.6% ( 878/1608 )
Functions    : 75.5% ( 413/547 )
Lines        : 78.67% ( 1870/2377 )
================================================================================
```
=> Use Istanbul to show code coverage at coverage/lcov-report/index.html

.babelrc, .eslintrc.js, package-lock.json, package.json, src/xregexp.js, tests/spec/s-xregexp-methods.js, tests/spec/s-xregexp.js
See https://github.com/slevithan/xregexp/commit/1050835ccb31fc370373994a1b09026bdc29b39b
and https://github.com/slevithan/xregexp/pull/241#issuecomment-384480732
I think this should close https://github.com/slevithan/xregexp/issues/224
~# TODO:~
=> BREAKING: Handle ES2018 capture names

README.md, src/xregexp.js, tests/.eslintrc.js, tests/helpers/h.js, tests/spec/s-addons-build.js, tests/spec/s-addons-matchrecursive.js, tests/spec/s-addons-unicode.js, tests/spec/s-xregexp-methods.js, tests/spec/s-xregexp.js, types/index.d.ts
Following up on the [change] to use ES2018 constraints on the names of capture groups,
this makes it so that XRegExp `namespacing` feature is enabled by
default, so that named capture group matches will appear on the
`.groups` property of the match object, rather than directly on the
match object, in accordance with the ES2018 spec.
While this is a breaking change, users can restore the old behavior by running:
XRegExp.uninstall('namespacing')
[change]: https://github.com/slevithan/xregexp/pull/247#issuecomment-757374810
=> BREAKING: Enable `namespacing` feature by default

README.md, package-lock.json, package.json, src/addons/build.js, src/addons/matchrecursive.js, src/addons/unicode-base.js, src/addons/unicode-categories.js, src/addons/unicode-properties.js, src/addons/unicode-scripts.js, src/xregexp.js
Changes include:
* BREAKING: Handle ES2018 capture names: https://github.com/slevithan/xregexp/pull/247
* BREAKING: Enable `namespacing` feature by default: https://github.com/slevithan/xregexp/pull/316
* BREAKING: Remove Unicode Blocks addon: https://github.com/slevithan/xregexp/commit/4860122362c9822f35ab7f2deea7973a5815fcac
* restore perf tweak that made a meaningful difference in regex construction perf tests: https://github.com/slevithan/xregexp/commit/5f182615a4d9e02e6c297e21ce51eda816494f77
* XRegExp.exec: preserve groups obj that comes from native ES2018 named capture: https://github.com/slevithan/xregexp/commit/c4a83e76fc3e1ab5a9053618267dff33edd1174e
* Make XRegExp.exec set groups prop to undefined if there are no named captures (closes #320): …
=> Bump version to 5.0.0
